"""Add topic_vocabulary

Revision ID: 569f8eb022c0
Revises: 8bb9227dee1c
Create Date: 2026-08-24 18:09:23.598543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '569f8eb022c0'
down_revision: Union[str, None] = '8bb9227dee1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intelligence_topics', sa.Column('topic_vocabulary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intelligence_topics', 'topic_vocabulary')
    # ### end Alembic commands ###
