"""add_event_metadata

Revision ID: d773745d5d7c
Revises: 569f8eb022c0
Create Date: 2026-08-27 16:04:55.667942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd773745d5d7c'
down_revision: Union[str, None] = '569f8eb022c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_subtype', sa.String(), nullable=True))
    op.add_column('events', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_metadata')
    op.drop_column('events', 'event_subtype')
    # ### end Alembic commands ###
