"""add_signal_type

Revision ID: ee03637b31c2
Revises: d773745d5d7c
Create Date: 2026-08-27 16:52:14.253499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee03637b31c2'
down_revision: Union[str, None] = 'd773745d5d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('signal_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'signal_type')
    # ### end Alembic commands ###
